services:
  db:
    image: postgres:16-alpine
    container_name: crud-learning-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: crud_learning_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Pakboys123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: crud-learning-pgadmin
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@crudlearning.local
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "True"
      PGADMIN_REPLACE_SERVERS_ON_STARTUP: "True"
      PGPASS_FILE: /tmp/pgpass
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json:ro
      - ./pgadmin/pgpass:/tmp/pgpass:ro

volumes:
  postgres_data:
  pgadmin_data: